/**
 * VS Code context file generation for Ralph mode.
 * Creates ralph-context.md with ticket info and workflow instructions.
 */

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { EnhancedPRDDocument } from "./prd-extraction";
import { WORKFLOW_PHASES, WORKFLOW_RULES, VERIFICATION_CHECKLIST } from "./ralph-prompts";

/**
 * Generate VS Code context markdown content.
 */
export function generateVSCodeContext(prd: EnhancedPRDDocument): string {
  const incompleteTickets = prd.userStories.filter((story) => !story.passes);
  const completedTickets = prd.userStories.filter((story) => story.passes);

  const ticketList = incompleteTickets
    .map((ticket) => {
      const priority = ticket.priority ? ` (${ticket.priority})` : "";
      return `- **${ticket.title}**${priority}\n  ID: \`${ticket.id}\``;
    })
    .join("\n");

  const epicHeader = prd.epicTitle ? `\n**Epic:** ${prd.epicTitle}` : "";

  return `# Ralph Context - ${prd.projectName}

> This file was auto-generated by Brain Dump for Ralph mode in VS Code.
> Read this file to understand the current task context.
${epicHeader}
**Generated:** ${new Date().toISOString()}

---

## Your Task

You are Ralph, an autonomous coding agent. Follow the Universal Quality Workflow:
${WORKFLOW_PHASES}
---

## Current Tickets

**Incomplete (${incompleteTickets.length}):**
${ticketList || "_No incomplete tickets_"}

**Completed (${completedTickets.length}):** ${completedTickets.map((t) => t.title).join(", ") || "_None_"}

---
${WORKFLOW_RULES}
---
${VERIFICATION_CHECKLIST}
---

## MCP Tools Available

- \`start_ticket_work(ticketId)\` - Creates branch, posts "Starting work" comment
- \`complete_ticket_work(ticketId, summary)\` - Updates status, posts summary, suggests next ticket
- \`add_ticket_comment(ticketId, content, author, type)\` - Add work notes

---

## Testing Requirements

${prd.testingRequirements.map((req) => `- ${req}`).join("\n")}

---

## Dev Server Management

When starting a dev server for testing or development:
1. Start with explicit port binding: \`pnpm dev --port 8100 --host 0.0.0.0\`
2. Update \`.ralph-services.json\` with service info (see schema below)
3. Use these port conventions:
   - 8100-8110: Frontend (Vite, Next.js, React)
   - 8200-8210: Backend (Express, Fastify, NestJS)
   - 8300-8310: Storybook, docs
   - 8400-8410: Databases (debugging)

When stopping a dev server:
1. Update \`.ralph-services.json\` to mark status as "stopped"

### .ralph-services.json Schema
\`\`\`json
{
  "services": [
    {
      "name": "vite-dev-server",
      "type": "frontend",
      "port": 8100,
      "status": "running",
      "healthEndpoint": "/",
      "startedAt": "2024-01-15T10:30:00Z"
    }
  ],
  "updatedAt": "2024-01-15T10:35:00Z"
}
\`\`\`
`;
}

/**
 * Write VS Code context file to project .claude directory.
 */
export async function writeVSCodeContext(
  projectPath: string,
  content: string
): Promise<{ success: true; path: string } | { success: false; message: string }> {
  const claudeDir = join(projectPath, ".claude");
  const contextPath = join(claudeDir, "ralph-context.md");

  try {
    mkdirSync(claudeDir, { recursive: true });
    writeFileSync(contextPath, content, "utf-8");
    return { success: true, path: contextPath };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error(`[brain-dump] Failed to write VS Code context file to ${contextPath}:`, error);
    return {
      success: false,
      message: `Failed to create Ralph context file in ${claudeDir}: ${message}. Check write permissions and disk space.`,
    };
  }
}
