/**
 * Shell completions generation from command registry.
 *
 * Generates completion scripts for zsh, bash, and fish
 * that users pipe into their shell config files.
 */

import { COMMAND_REGISTRY, type CommandDef } from "../lib/command-registry.ts";

const SHELLS = ["zsh", "bash", "fish"] as const;
type Shell = (typeof SHELLS)[number];

// ── Helpers ───────────────────────────────────────────────────

/** Get unique resource names (excluding _top). */
function getResources(): string[] {
  const seen = new Set<string>();
  for (const cmd of COMMAND_REGISTRY) {
    if (cmd.resource !== "_top") seen.add(cmd.resource);
  }
  return [...seen].sort();
}

/** Get top-level command names (resource === "_top"). */
function getTopLevelCommands(): string[] {
  return COMMAND_REGISTRY.filter((c) => c.resource === "_top")
    .map((c) => c.action)
    .sort();
}

/** Get commands grouped by resource. */
function getCommandsByResource(): Map<string, CommandDef[]> {
  const map = new Map<string, CommandDef[]>();
  for (const cmd of COMMAND_REGISTRY) {
    if (cmd.resource === "_top") continue;
    const list = map.get(cmd.resource) ?? [];
    list.push(cmd);
    map.set(cmd.resource, list);
  }
  return map;
}

/** Get all flags for a specific resource+action pair. */
function getFlagNames(cmd: CommandDef): string[] {
  return cmd.flags.map((f) => `--${f.name}`);
}

// Backward-compatible top-level aliases
const BACKWARD_COMPAT = ["backup", "restore", "check", "doctor", "export", "import"];

// ── ZSH ───────────────────────────────────────────────────────

function generateZsh(): string {
  const resources = getResources();
  const topLevel = getTopLevelCommands();
  const byResource = getCommandsByResource();

  const allFirstWords = [
    ...new Set([...resources, ...topLevel, ...BACKWARD_COMPAT, "help", "completions"]),
  ].sort();

  const lines: string[] = [
    "#compdef brain-dump",
    "# Generated by: brain-dump completions zsh",
    '# Add to ~/.zshrc: eval "$(brain-dump completions zsh)"',
    "",
    "_brain-dump() {",
    "  local -a commands",
    '  local curcontext="$curcontext" state line',
    "",
    "  _arguments -C \\",
    "    '1:command:->command' \\",
    "    '2:action:->action' \\",
    "    '*:flags:->flags'",
    "",
    "  case $state in",
    "    command)",
    `      commands=(${allFirstWords.map((w) => `'${w}'`).join(" ")})`,
    "      _describe 'command' commands",
    "      ;;",
    "    action)",
    "      case $line[1] in",
  ];

  // Resource-specific actions
  for (const [resource, cmds] of byResource) {
    const actions = cmds.map((c) => c.action).sort();
    lines.push(`        ${resource})`);
    lines.push(`          local -a actions=(${actions.map((a) => `'${a}'`).join(" ")})`);
    lines.push("          _describe 'action' actions");
    lines.push("          ;;");
  }

  lines.push(
    "        completions)",
    `          local -a shells=('zsh' 'bash' 'fish')`,
    "          _describe 'shell' shells",
    "          ;;",
    "      esac",
    "      ;;",
    "    flags)",
    "      local -a flags",
    '      case "$line[1]:$line[2]" in'
  );

  // Per-command flag completions
  for (const cmd of COMMAND_REGISTRY) {
    if (cmd.resource === "_top") {
      const flagNames = getFlagNames(cmd);
      if (flagNames.length > 0) {
        lines.push(`        ${cmd.action}:*)`);
        lines.push(`          flags=(${flagNames.map((f) => `'${f}'`).join(" ")})`);
        lines.push("          _describe 'flag' flags");
        lines.push("          ;;");
      }
    } else {
      const flagNames = getFlagNames(cmd);
      if (flagNames.length > 0) {
        lines.push(`        ${cmd.resource}:${cmd.action})`);
        lines.push(`          flags=(${flagNames.map((f) => `'${f}'`).join(" ")})`);
        lines.push("          _describe 'flag' flags");
        lines.push("          ;;");
      }
    }
  }

  lines.push("      esac", "      ;;", "  esac", "}", "", "_brain-dump");

  return lines.join("\n");
}

// ── Bash ──────────────────────────────────────────────────────

function generateBash(): string {
  const resources = getResources();
  const topLevel = getTopLevelCommands();
  const byResource = getCommandsByResource();

  const allFirstWords = [
    ...new Set([...resources, ...topLevel, ...BACKWARD_COMPAT, "help", "completions"]),
  ].sort();

  const lines: string[] = [
    "# Generated by: brain-dump completions bash",
    '# Add to ~/.bashrc: eval "$(brain-dump completions bash)"',
    "",
    "_brain_dump() {",
    "  local cur prev words cword",
    "  _init_completion || return",
    "",
    "  # Position 1: resource or top-level command",
    "  if [[ $cword -eq 1 ]]; then",
    `    COMPREPLY=($(compgen -W '${allFirstWords.join(" ")}' -- "$cur"))`,
    "    return",
    "  fi",
    "",
    '  local resource="${words[1]}"',
    "",
    "  # Position 2: action",
    "  if [[ $cword -eq 2 ]]; then",
    '    case "$resource" in',
  ];

  for (const [resource, cmds] of byResource) {
    const actions = cmds.map((c) => c.action).sort();
    lines.push(`      ${resource})`);
    lines.push(`        COMPREPLY=($(compgen -W '${actions.join(" ")}' -- "$cur"))`);
    lines.push("        ;;");
  }

  lines.push(
    "      completions)",
    "        COMPREPLY=($(compgen -W 'zsh bash fish' -- \"$cur\"))",
    "        ;;",
    "    esac",
    "    return",
    "  fi",
    "",
    "  # Position 3+: flags",
    '  local action="${words[2]}"',
    "  local flags=''",
    '  case "$resource:$action" in'
  );

  // Per-command flag completions
  for (const cmd of COMMAND_REGISTRY) {
    const flagNames = getFlagNames(cmd);
    if (flagNames.length === 0) continue;

    if (cmd.resource === "_top") {
      // Top-level commands have action in position 1, flags start at position 2
      lines.push(`    ${cmd.action}:*)`);
    } else {
      lines.push(`    ${cmd.resource}:${cmd.action})`);
    }
    lines.push(`      flags='${flagNames.join(" ")}'`);
    lines.push("      ;;");
  }

  lines.push(
    "  esac",
    "",
    '  if [[ -n "$flags" ]]; then',
    '    COMPREPLY=($(compgen -W "$flags" -- "$cur"))',
    "  fi",
    "}",
    "",
    "complete -F _brain_dump brain-dump"
  );

  return lines.join("\n");
}

// ── Fish ──────────────────────────────────────────────────────

function generateFish(): string {
  const resources = getResources();
  const topLevel = getTopLevelCommands();
  const byResource = getCommandsByResource();

  const allFirstWords = [
    ...new Set([...resources, ...topLevel, ...BACKWARD_COMPAT, "help", "completions"]),
  ].sort();

  const lines: string[] = [
    "# Generated by: brain-dump completions fish",
    "# Add to ~/.config/fish/completions/brain-dump.fish",
    "",
    "# Disable file completions by default",
    "complete -c brain-dump -f",
    "",
    "# First argument: resources and top-level commands",
  ];

  for (const word of allFirstWords) {
    lines.push(`complete -c brain-dump -n '__fish_use_subcommand' -a '${word}'`);
  }

  lines.push("", "# Resource actions");

  for (const [resource, cmds] of byResource) {
    for (const cmd of cmds) {
      lines.push(
        `complete -c brain-dump -n '__fish_seen_subcommand_from ${resource}' -a '${cmd.action}' -d '${escapeQuotes(cmd.description)}'`
      );
    }
  }

  // completions sub-command
  lines.push(
    "",
    "# completions shells",
    "complete -c brain-dump -n '__fish_seen_subcommand_from completions' -a 'zsh bash fish'"
  );

  lines.push("", "# Flags per command");

  for (const cmd of COMMAND_REGISTRY) {
    for (const flag of cmd.flags) {
      if (cmd.resource === "_top") {
        lines.push(
          `complete -c brain-dump -n '__fish_seen_subcommand_from ${cmd.action}' -l '${flag.name}' -d '${escapeQuotes(flag.description)}'`
        );
      } else {
        lines.push(
          `complete -c brain-dump -n '__fish_seen_subcommand_from ${cmd.resource}; and __fish_seen_subcommand_from ${cmd.action}' -l '${flag.name}' -d '${escapeQuotes(flag.description)}'`
        );
      }
    }
  }

  return lines.join("\n");
}

function escapeQuotes(s: string): string {
  return s.replace(/'/g, "\\'");
}

// ── Public handler ────────────────────────────────────────────

export function handle(action: string, _args: string[]): void {
  const shell = action as Shell;

  if (!SHELLS.includes(shell)) {
    console.error(`Usage: brain-dump completions <zsh|bash|fish>`);
    console.error(`\nGenerates a shell completion script. Pipe the output to your shell config:`);
    console.error(`  brain-dump completions zsh >> ~/.zshrc`);
    console.error(`  brain-dump completions bash >> ~/.bashrc`);
    console.error(`  brain-dump completions fish > ~/.config/fish/completions/brain-dump.fish`);
    process.exit(1);
  }

  switch (shell) {
    case "zsh":
      console.log(generateZsh());
      break;
    case "bash":
      console.log(generateBash());
      break;
    case "fish":
      console.log(generateFish());
      break;
  }
}
