#!/usr/bin/env node
/**
 * fetch-fonts.mjs — Self-host the app's fonts (provenance + regeneration).
 *
 * Brain Dump is local-first, so typography must not depend on the Google Fonts
 * CDN at runtime. This script downloads the WOFF2 subsets we actually use
 * (Fira Sans + Fira Code) into `public/fonts/` and regenerates the
 * `@font-face` rules in `src/styles/fonts.css`, preserving Google's
 * `unicode-range` subsetting so the browser only loads needed glyphs.
 *
 * Run manually when bumping font versions or adding a weight/subset:
 *   node scripts/fetch-fonts.mjs
 *
 * It is NOT part of the build — the committed WOFF2 files and fonts.css are the
 * source of truth. This script only exists to reproduce them.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Matches the exact family/axis/weights the app declares in __root.tsx today.
const GOOGLE_FONTS_CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&family=Fira+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&display=swap";

// A modern Chrome UA is required for Google Fonts to serve WOFF2 (older UAs get
// TTF/WOFF). Keep this current if Google ever changes its negotiation.
const CHROME_UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Latin coverage is enough for this English-first dev tool; latin-ext adds the
// accented Western/Central-European glyphs that show up in user content. We
// deliberately skip cyrillic/greek/vietnamese/symbols to keep the payload small.
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const FONTS_DIR = resolve(ROOT, "public/fonts");
const CSS_OUT = resolve(ROOT, "src/styles/fonts.css");

/** Parse the Google Fonts CSS into structured @font-face descriptors. */
function parseFontFaces(css) {
  const faces = [];
  // Each block is preceded by a `/* subset */` comment.
  const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = blockRe.exec(css)) !== null) {
    const subset = m[1];
    const body = m[2];
    const field = (name) => {
      const fm = body.match(new RegExp(`${name}:\\s*([^;]+);`));
      return fm ? fm[1].trim() : "";
    };
    const family = field("font-family").replace(/['"]/g, "");
    const style = field("font-style");
    const weight = field("font-weight");
    const unicodeRange = field("unicode-range");
    const urlMatch = body.match(/url\(([^)]+)\)/);
    const url = urlMatch ? urlMatch[1].replace(/['"]/g, "") : "";
    faces.push({ subset, family, style, weight, unicodeRange, url });
  }
  return faces;
}

/** Deterministic, human-readable local filename for a font face. */
function fileNameFor({ family, weight, style, subset }) {
  const slug = family.toLowerCase().replace(/\s+/g, "-");
  // Variable axis weights look like "300 700" — collapse to "300-700".
  const weightSlug = weight.replace(/\s+/g, "-");
  return `${slug}-${weightSlug}-${style}-${subset}.woff2`;
}

async function main() {
  console.log("Fetching Google Fonts CSS…");
  const cssRes = await fetch(GOOGLE_FONTS_CSS_URL, { headers: { "User-Agent": CHROME_UA } });
  if (!cssRes.ok) throw new Error(`Google Fonts CSS request failed: ${cssRes.status}`);
  const css = await cssRes.text();

  const faces = parseFontFaces(css).filter((f) => KEEP_SUBSETS.has(f.subset));
  if (faces.length === 0) throw new Error("No matching font faces parsed — did the CSS format change?");

  await mkdir(FONTS_DIR, { recursive: true });

  const rules = [];
  for (const face of faces) {
    const fileName = fileNameFor(face);
    console.log(`Downloading ${fileName} (${face.subset})…`);
    const res = await fetch(face.url, { headers: { "User-Agent": CHROME_UA } });
    if (!res.ok) throw new Error(`Font download failed (${face.url}): ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    await writeFile(resolve(FONTS_DIR, fileName), buf);

    rules.push(
      [
        `/* ${face.family} ${face.weight} ${face.style} — ${face.subset} */`,
        `@font-face {`,
        `  font-family: "${face.family}";`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        `  font-display: swap;`,
        `  src: url("/fonts/${fileName}") format("woff2");`,
        `  unicode-range: ${face.unicodeRange};`,
        `}`,
      ].join("\n")
    );
  }

  const header = [
    "/**",
    " * Self-hosted web fonts — GENERATED by scripts/fetch-fonts.mjs. Do not edit by hand.",
    " *",
    " * Fira Sans + Fira Code, latin + latin-ext subsets, served from /public/fonts.",
    " * Replaces the render-blocking Google Fonts <link> so first paint needs no network.",
    " */",
    "",
  ].join("\n");

  await writeFile(CSS_OUT, header + rules.join("\n\n") + "\n");
  console.log(`\nWrote ${faces.length} WOFF2 files to public/fonts/ and ${CSS_OUT}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
