#!/usr/bin/env npx tsx

/**
 * Generate docs/cli.md from the command registry.
 *
 * Usage:
 *   npx tsx scripts/generate-cli-docs.ts          # write to docs/cli.md
 *   npx tsx scripts/generate-cli-docs.ts --check   # exit 1 if docs are stale
 *   npx tsx scripts/generate-cli-docs.ts --stdout   # print to stdout
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  COMMAND_REGISTRY,
  getResources,
  getCommandsForResource,
  getResourceDescription,
} from "../cli/lib/command-registry.ts";
import type { CommandDef, FlagDef } from "../cli/lib/command-registry.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "..");
const OUTPUT = resolve(ROOT, "docs/cli.md");

// ── Markdown generation ───────────────────────────────────────

function formatFlag(f: FlagDef): string {
  if (f.type === "boolean") {
    return f.required ? `--${f.name}` : `[--${f.name}]`;
  }
  const valHint = f.enum ? f.enum.join("|") : f.type === "number" ? "n" : "value";
  return f.required ? `--${f.name} <${valHint}>` : `[--${f.name} <${valHint}>]`;
}

function flagsTable(flags: FlagDef[]): string {
  if (flags.length === 0) return "_No flags._\n";

  const rows = flags.map((f) => {
    const req = f.required ? "Yes" : "No";
    const desc = f.enum ? `${f.description} (${f.enum.join(", ")})` : f.description;
    return `| \`--${f.name}\` | ${f.type} | ${req} | ${desc} |`;
  });

  return (
    ["| Flag | Type | Required | Description |", "| --- | --- | --- | --- |", ...rows].join("\n") +
    "\n"
  );
}

function commandSection(cmd: CommandDef, isTopLevel: boolean): string {
  const lines: string[] = [];

  // Heading
  const usage = isTopLevel
    ? `brain-dump ${cmd.action}`
    : `brain-dump ${cmd.resource} ${cmd.action}`;
  lines.push(`### ${usage}\n`);
  lines.push(`${cmd.description}\n`);

  // Usage with flags
  const flagHints = cmd.flags.map(formatFlag).join(" ");
  lines.push("```bash");
  lines.push(`${usage} ${flagHints}`.trimEnd());
  lines.push("```\n");

  // Aliases
  if (cmd.aliases && cmd.aliases.length > 0) {
    lines.push(`**Aliases:** ${cmd.aliases.map((a) => `\`${a}\``).join(", ")}\n`);
  }

  // Flags table
  lines.push(flagsTable(cmd.flags));

  // Examples
  if (cmd.examples && cmd.examples.length > 0) {
    lines.push("**Examples:**\n");
    lines.push("```bash");
    for (const ex of cmd.examples) {
      lines.push(ex);
    }
    lines.push("```\n");
  }

  return lines.join("\n");
}

function generateDocs(): string {
  const sections: string[] = [];

  // Header
  sections.push(`<!-- AUTO-GENERATED by scripts/generate-cli-docs.ts — do not edit manually -->\n`);
  sections.push("# CLI Reference\n");
  sections.push(
    "Brain Dump CLI provides full resource management, database utilities, and developer workflow commands.\n"
  );
  sections.push("All commands output JSON by default. Add `--pretty` for human-readable output.\n");

  // Quick reference table
  sections.push("## Quick Reference\n");
  const resources = getResources().filter((r) => r !== "_top");
  const topCommands = getCommandsForResource("_top");

  sections.push("### Resources\n");
  sections.push("| Resource | Description |");
  sections.push("| --- | --- |");
  for (const r of resources) {
    const desc = getResourceDescription(r);
    const actions = getCommandsForResource(r)
      .map((c) => c.action)
      .join(", ");
    sections.push(`| \`${r}\` | ${desc} — _${actions}_ |`);
  }
  sections.push("");

  sections.push("### Top-Level Commands\n");
  sections.push("| Command | Description |");
  sections.push("| --- | --- |");
  for (const cmd of topCommands) {
    sections.push(`| \`brain-dump ${cmd.action}\` | ${cmd.description} |`);
  }
  sections.push("");

  sections.push("### Backward-Compatible Shortcuts\n");
  sections.push("| Shortcut | Equivalent |");
  sections.push("| --- | --- |");
  sections.push("| `brain-dump backup` | `brain-dump admin backup` |");
  sections.push("| `brain-dump restore` | `brain-dump admin restore` |");
  sections.push("| `brain-dump check` | `brain-dump admin check` |");
  sections.push("| `brain-dump doctor` | `brain-dump admin doctor` |");
  sections.push(
    "| `brain-dump export --epic <id>` | `brain-dump transfer export-epic --epic <id>` |"
  );
  sections.push(
    "| `brain-dump import --file <path>` | `brain-dump transfer import --file <path>` |"
  );
  sections.push("");

  // ── Top-level commands section ──
  sections.push("---\n");
  sections.push("## Top-Level Commands\n");
  for (const cmd of topCommands) {
    sections.push(commandSection(cmd, true));
  }

  // ── Resource sections ──
  for (const r of resources) {
    sections.push("---\n");
    sections.push(`## ${r}\n`);
    sections.push(`${getResourceDescription(r)}\n`);

    const commands = getCommandsForResource(r);
    for (const cmd of commands) {
      sections.push(commandSection(cmd, false));
    }
  }

  // ── Environment section ──
  sections.push("---\n");
  sections.push("## Environment\n");
  sections.push("The CLI uses XDG-compliant paths:\n");
  sections.push("| OS | Database | State (backups, logs) |");
  sections.push("| --- | --- | --- |");
  sections.push("| Linux | `~/.local/share/brain-dump/` | `~/.local/state/brain-dump/` |");
  sections.push("| macOS | `~/Library/Application Support/brain-dump/` | Same |");
  sections.push("| Windows | `%APPDATA%\\brain-dump\\` | Same |");
  sections.push("");
  sections.push("The CLI shares the database with the Brain Dump web UI and MCP server.\n");

  // ── Exit codes ──
  sections.push("## Exit Codes\n");
  sections.push("| Code | Meaning |");
  sections.push("| --- | --- |");
  sections.push("| 0 | Success |");
  sections.push("| 1 | Error (validation, database, etc.) |");
  sections.push("");

  return sections.join("\n") + "\n";
}

// ── CLI ───────────────────────────────────────────────────────

const args = process.argv.slice(2);
const checkMode = args.includes("--check");
const stdoutMode = args.includes("--stdout");

const generated = generateDocs();

if (stdoutMode) {
  process.stdout.write(generated);
  process.exit(0);
}

if (checkMode) {
  let existing = "";
  try {
    existing = readFileSync(OUTPUT, "utf-8");
  } catch {
    // file doesn't exist
  }
  if (existing !== generated) {
    console.error("docs/cli.md is stale. Run: npx tsx scripts/generate-cli-docs.ts");
    process.exit(1);
  }
  console.log("docs/cli.md is up to date.");
  process.exit(0);
}

// Default: write
writeFileSync(OUTPUT, generated, "utf-8");
console.log(`Generated ${OUTPUT}`);
const cmdCount = COMMAND_REGISTRY.length;
const resourceCount = getResources().filter((r) => r !== "_top").length;
const topCount = getCommandsForResource("_top").length;
console.log(
  `  ${resourceCount} resources, ${topCount} top-level commands, ${cmdCount} total commands`
);
